### ISSUE TITLE
kernel fails to install with error libssl.so.1.0.0 undefined symbol: EVP_idea_cbc

### ISSUE THREAD

**Issue by imatlab-helper** [anntzer/imatlab#3]
On Ubuntu xenial 16.04 on x64 with matlab r2016b, the current PyPi version of imatlab fails to install the kernel. The `pip install` command succeeds, but the `python -m imatlab install` command fails. The errors include:
````
ImportError: No module named 'matlabengineforpython3_5'
ImportError: [...] bin/glnxa64/libssl.so.1.0.0: undefined symbol: EVP_idea_cbc
OSError: Please reinstall MATLAB Engine for Python or contact MathWorks Technical Support for assistance: [...] bin/glnxa64/libssl.so.1.0.0: undefined symbol: EVP_idea_cbc
````

This problem appears to affect any kernel utilizing the python matlab engine, impacting both the imatlab kernel and the matlab MetaKernel maintained by @Calysto.

**Comment by imatlab-helper** [comment]
This can be solved by using the Linux system's version of libssl.so.1.0.0 instead of the one that ships with matlab r2016b. In ubuntu xenial, replace the file `<matlabroot>/bin/glnxa64/libssl.so.1.0.0` with the one in the system located at `/lib/x86_64-linux-gnu/libssl.so.1.0.0`

**Comment by anntzer** [comment]
MATLAB tends to ship somewhat outdated libraries (and load them with LD_LIBRARY_PATH, which then affects Python, which needs a newer version).  In general, for this kind of issues, you can either replace the MATLAB-shipped library as you did, or rely on LD_PRELOAD to, well, preload the new library first.

**Comment by steverweber** [comment]
also hity this error... perhaps be nice to put this in the readme.
```
cp /lib/x86_64-linux-gnu/libssl.so.1.0.0  /usr/local/MATLAB/R2016b/bin/glnxa64/libssl.so.1.0.0
cp /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/local/MATLAB/R2016b/bin/glnxa64/libcrypto.so.1.0.0
```

**Comment by imatlab-helper** [comment]
Yea, this is a rotten bug. I wonder if there's a way we can identify the place to set this for the kernel so that when it calls matlab, we also include the ```LD_LIBRARY_PATH``` prefix so that we don't have to muck with matlab distribution files. Someplace in ```kernel.json``` perhaps?

**Comment by anntzer** [comment]
I think adding something like
```
import importlib
from pathlib import Path

# Need to check what the path is on other OSes.
for n in [p.name.split(".")[0] for p in Path("/usr/lib/python3.6/lib-dynload").iterdir()]:
    try:
        importlib.import_module(n)
    except ImportError:
        pass
```
at the beginning of `_kernel.py` (before importing the matlab module) would help.  (This only takes ~50ms so it's not a performance issue).

Please check whether that works for you.  Replacing the `.so`s is not a solution as not everyone is superuser.

**Comment by anntzer** [comment]
Although this should already not be an issue anymore with the git version (because plotly will import ssl before matlab messes up the path).  @steverweber, were you using git master or 0.1?

**Comment by imatlab-helper** [comment]
Confirmed that for the git version, this works with an unmodified R2016b matlabroot.
