### ISSUE TITLE
kernel dead: kernel restarting indefinitely

### ISSUE THREAD

**Issue by imatlab-helper** [anntzer/imatlab#4]
Hi @anntzer,

Thank you for your time in creating/maintaining this kernel and the metakernel version. They are very valuable and will help a great number of students, scientists, and academics.

I am unable to run the imatlab kernel, both the PyPi and git master versions exhibit the same problem.

System is stock Ubuntu Xenial 16.04.2 LTS on x64 with matlab r2016b. I am running in a python3.5 virtualenv. jupyter notebooks for a python3 kernel and the Calysto MetaKernel work. plotly offline plots works without issue in the python3 jupyter notebooks. As the Calysto MetaKernel now also relies on the python matlab engine, I have successfully installed the matlabpythonengine package to the virtual environment. In standard python in the virtualenv, I can do `import matlab.engine`, call `start_matlab()` and matlab functions perform as expected. I can confirm that a matlab process is running in the background via `ps` while the engine is up and shuts down when I quit python. Importing plotly from standard python works. The plotly matlab toolbox is also confirmed working in matlab (e.g., `fig2plotly` is in the matlab path).

The imatlab kernel from git master times out on waiting for `kernel_info`.
Regardless of whether I install the PyPi version or the git master, the kernel does not work. I can confirm that the kernel option appears in the jupyter dropdown list when I choose to launch a new notebook. However, after launching a new imatlab notebook, even though I see matlab being started on the system via `ps`, the debug output from jupyter notes:
````
[W 17:19:48.299 NotebookApp] Timeout waiting for kernel_info reply from [...]
````
It then proceeds to restart the matlab kernel. It succeeds in restarting, but then times out again, and starts the process all over again.

Any thoughts? Thank you for any help.

**Comment by anntzer** [comment]
Thank you for your detailed report.  Let's try things one at a time.
Does the echo kernel (https://github.com/jupyter/echo_kernel) work for you?

**Comment by imatlab-helper** [comment]
Yup, echo_kernel shows up as Python 3 and that kernel works just fine.

**Comment by anntzer** [comment]
If you apply the following patch to git master, does anything get printed to /tmp/foo?
```
diff --git a/imatlab/_kernel.py b/imatlab/_kernel.py
index 85e6ce0..e5669c3 100644
--- a/imatlab/_kernel.py
+++ b/imatlab/_kernel.py
@@ -90,6 +90,8 @@ class MatlabKernel(Kernel):
         # We also hook this property to `cd` into the current directory.
         if "cd" in self._options:
             self._call("cd", str(Path().resolve()))
+        print("here", file=open("/tmp/foo", "a"))
+        print(self._call("version"), file=open("/tmp/foo", "a"))
         return {
             "name": "matlab",
             "version": self._call("version"),
```

**Comment by imatlab-helper** [comment]
No, the `/tmp/foo` file does not get created at all.

**Comment by anntzer** [comment]
Try replacing the `@property def language_info` by a class-level variable also named `language_info` and with the same fields (just make up something for "version").  Does that help?

What does `python -mpip list --outdated` show?  (This may just be due to version dependencies being not strict enough.)

**Comment by imatlab-helper** [comment]
`python -mpip list --outdated` doesn't list anything other than a deprecated format warning (the virtualenv was just created yesterday).

I don't know if I replaced language_info correctly, but I tried this:
````
    def language_info(self):
        return {
            "name": "matlab",
            "version": "five",
            "mimetype": "text/x-matlab",
            "file_extension": ".m",
            "pygments_lexer": "matlab",
            "codemirror_mode": "octave",
            "nbconvert_exporter": "imatlab._exporter.MatlabExporter",
        }
````
but it did not help. Same behavior.

**Comment by anntzer** [comment]
I meant
```
diff --git a/imatlab/_kernel.py b/imatlab/_kernel.py
index 85e6ce0..dcd19d7 100644
--- a/imatlab/_kernel.py
+++ b/imatlab/_kernel.py
@@ -85,20 +85,15 @@ class MatlabKernel(Kernel):
         """
         return self._engine.builtin(*args, **kwargs)
 
-    @property
-    def language_info(self):
-        # We also hook this property to `cd` into the current directory.
-        if "cd" in self._options:
-            self._call("cd", str(Path().resolve()))
-        return {
-            "name": "matlab",
-            "version": self._call("version"),
-            "mimetype": "text/x-matlab",
-            "file_extension": ".m",
-            "pygments_lexer": "matlab",
-            "codemirror_mode": "octave",
-            "nbconvert_exporter": "imatlab._exporter.MatlabExporter",
-        }
+    language_info = {
+        "name": "matlab",
+        "version": "123",
+        "mimetype": "text/x-matlab",
+        "file_extension": ".m",
+        "pygments_lexer": "matlab",
+        "codemirror_mode": "octave",
+        "nbconvert_exporter": "imatlab._exporter.MatlabExporter",
+    }
 
     def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)
```

Also try running, from a normal python prompt, `eng = matlab.engine.start_matlab(); eng.builtin("version")`, as well as `eng.version()`.

**Comment by imatlab-helper** [comment]
The `language_info` variable defined as described did not appear to change anything. Same behavior.

````
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matlab.engine
>>> eng = matlab.engine.start_matlab()
>>> eng.builtin("version")
'9.1.0.441655 (R2016b)'
>>> eng.version()
'9.1.0.441655 (R2016b)'
````

**Comment by anntzer** [comment]
Try launching a console or qtconsole frontend rather than a notebook, i.e.
```
$ jupyter console --kernel=imatlab
$ jupyter qtconsole --kernel=imatlab
```

**Comment by imatlab-helper** [comment]
````
$ jupyter console --debug --kernel=imatlab
[...]
[ZMQTerminalIPythonApp] Starting kernel: ['[...]bin/python', '-m', 'imatlab', '-f', '/run/user/[...]/jupyter/kernel-30576.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:57942
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:41392
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:41392
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:48139
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:48139
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:56503
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:56503
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:39255
````
it just hangs there for a while, after a minute or two, it gives up and quits, outputting:
````
Traceback (most recent call last):
  File "[venv]/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 321, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "[venv]/lib/python3.5/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "[venv]/lib/python3.5/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[venv]/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "[venv]/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "[venv]/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "[venv]/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "[venv]/lib/python3.5/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "[venv]/lib/python3.5/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "[venv]/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "[venv]/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 270, in __init__
    self.init_kernel_info()
  File "[venv]/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 324, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
````

I see the same behavior regardless of whether `language_info` was patched or unpatched.

**Comment by anntzer** [comment]
See the implementation of `MatlabKernel.__init__` (starting at line 103).  Using the `print("...", file=...)` technique as suggested above, can you figure out if the function is entered at all?  If it stalls at a certain statement?  (You need to redirect the output to a file as the frontend will redirect stdout/stderr.)

**Comment by imatlab-helper** [comment]
Found the culprit. It was the very last line of the `__init__` function:
`self._history = MatlabHistory(Path(self._call("prefdir")))`

If I comment that out, the console and notebook both work. It complains about some problem about `MatlabKernel` object not having attribute `_history`, but I imagine that's because I commented it out.

**Comment by anntzer** [comment]
Great, now you get to do the same check with `MatlabHistory.__init__` :-)

**Comment by imatlab-helper** [comment]
This is the line holding things up:
`self._et = ET.parse(str(prefdir / "History.xml"))`

**Comment by anntzer** [comment]
Do you have a huge `~/.matlab/R2016b/History.xml`? (e.g. how many lines?)

**Comment by imatlab-helper** [comment]
I do not have a `History.xml` file, only a `history.m`

**Comment by anntzer** [comment]
Can you check that `prefdir` is indeed `~/.matlab/R2016b`?  Regardless of what it is, what happens if you run in a normal python console `from xml.etree import ElementTree as ET; ET.parse("...")` where ... is the path above?

**Comment by imatlab-helper** [comment]
````
$ ls -a .matlab/R2016b/
.  ..  creation.timestamp  history.m  HtmlPanel  matlab.settings  mwKeyStore  thisMatlab.pem  toolbox_cache-9.1.0-4184284682-glnxa64.xml
````

**Comment by imatlab-helper** [comment]
`prefdir` does indeed point to the correct absolute path going to `.matlab/R2016b`.

````
>>> from xml.etree import ElementTree as ET
>>> ET.parse("[...]/.matlab/R2016b")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
    source = open(source, "rb")
IsADirectoryError: [Errno 21] Is a directory: '[...]/.matlab/R2016b'
````
````
>>> ET.parse("[...]/.matlab/R2016b/history.m")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
````
````
>>> ET.parse("[...]/.matlab/R2016b/History.xml")                                                                                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '[...]/R2016b/History.xml'
````

**Comment by anntzer** [comment]
Ah... in the MATLAB GUI, if you go to preferences -> command history, is "don't save history file" ticked?

**Comment by imatlab-helper** [comment]
No idea, this is a headless server and doesn't ever run the GUI. It's performing whatever the default behavior is for matlab running out of the box in strict console mode.

**Comment by imatlab-helper** [comment]
Perhaps useful: there is the history of prior matlab sessions in the `history.m` file, but no `History.xml` file exists.

**Comment by anntzer** [comment]
Ah... that's the reason.  I pushed a new commit that makes reading History.xml optional.

In console mode, MATLAB writes the history to history.m.  In graphical mode, it writes it to History.xml.  In fact the two files aren't even synchronized(!)  (Yes, that's a bit insane.)

Right now, the code loads the history from History.xml (only), for two reasons:
- it is likely to be the correct history file for most users.
- history.m doesn't actually store multiline inputs as a single unit (they are stored as separate lines, which I guess could be split by parsing them as complete MATLAB statements (see `do_is_complete`) but that's not implemented so far), whereas History.xml stores multiline inputs as individual units.
(Of course it's not really possible to merge two different history files either).

The code *updates* both history files, though... as long as both are present (because the header of History.xml has to use a very specific syntax, as it appears that MATLAB doesn't actually use a real xml parser but more likely just a pile of (poorly written) regexes).

With my new commit (please give it a try), in your case, only history.m will be updated (so later MATLAB console sessions will see them), but that history won't be loaded by later jupyter imatlab sessions.  You are welcome to submit a new PR that properly splits up history.m into individual chunks and loads it in case History.xml is not present (let me know if you need help, but I probably won't implement it myself in the near future at least).

**Comment by imatlab-helper** [comment]
Yup, it works. console and notebook are now functional. All set!
Plotly plotting works very nicely too. I'm just getting a peculiar warning that I'll describe in the other issue.

**Comment by anntzer** [comment]
(I guess that if your primary environment is the notebook, the lack of history is not really an issue...)

**Comment by imatlab-helper** [comment]
Yup, that's the goal. Most of the work is done via the console, as these are remote computational servers. Getting notebook support would be a very nice feature as interactive data visualization is a real challenge otherwise. This is looking great!
